#!/usr/bin/env ruby

BIN_DIR = File.dirname(File.symlink?(__FILE__) ? File.readlink(__FILE__) : __FILE__)
TOP_DIR = File.join(BIN_DIR, '..')
$: << File.join(TOP_DIR, 'lib')

DESCR = %{
Remove a topic/queue or a set of topics/queues from RabbitMQ Broker.

}

# The following is to work around a bug in activesupport triggered by
# the JWT library which is used only in the AMQP transport, os it
# fails quietly if that library is not installed in XMPP deployments
begin; require 'json/jwt'; rescue Exception; end


require 'optparse'
require 'omf_common'
require 'highline/import'
require 'net/http'
require 'cgi'

OP_MODE = :development

opts = {
    communication: {
        #url: 'xmpp://srv.mytestbed.net',
        #auth: {}
    },
    eventloop: { type: :em},
    logging: {
        level: 'info'
    }
}

@user = nil
@password = nil
config = nil

op = OptionParser.new
op.banner = "Usage: #{op.program_name} [options] topic1 topic2 ...\n#{DESCR}\n"
op.on '-f', '--file FILE NAME', "Configuration file" do |f|
  config = YAML.load_file(f)
end

op.on '-u', '--user USERNAME', "Username of rabbitmq" do |u|
  @user = u
end

op.on '-p', '--password PASSWORD', "Password to rabbitmq user given in -u" do |p|
  @password = p
end

op.on_tail('-h', "--help", "Show this message") { $stderr.puts op; exit }
op.parse(ARGV)

unless config and @user and @password
  $stderr.puts "ERROR: Missing declaration of --file\n\n"
  $stderr.puts op
  exit(-1)
end

def get_request(url)
  puts "GET #{url}\n"

  uri = URI.parse(url)
  http = Net::HTTP.new(address=uri.host, port=uri.port)

  request = Net::HTTP::Get.new(uri.request_uri, initheader = {'Content-Type' =>'application/json'})
  request.basic_auth @user, @password

  response = http.request(request)

  body = JSON.parse(response.body)
  body
end

def put_request(url, res_desc)
  puts "PUT all topics\n"

  uri = URI.parse(url)
  http = Net::HTTP.new(address=uri.host, port=uri.port)

  request = Net::HTTP::Put.new(uri.request_uri, initheader = {'Content-Type' =>'application/json'})
  request.basic_auth @user, @password
  request.body = res_desc.to_json

  response = http.request(request)

  body = JSON.parse(response.body)
  puts body
  body
end

def filter_topics_with_pattern(topics, pattern, scape=false)
  if pattern == "*"
    topics
  else
    regex = nil
    unless scape
      regex = /#{pattern}/
    else
      regex = Regexp.new(Regexp.quote(pattern))
    end
    topics.select { |topic| topic["name"] =~ regex }
  end
end

def delete_request(url)
  puts "DELETE #{url}\n"

  uri = URI.parse(url)
  http = Net::HTTP.new(uri.host, uri.port)

  request = Net::HTTP::Delete.new(uri.request_uri, initheader = {'Content-Type' =>'application/json'})
  request.basic_auth @user, @password

  response = http.request(request)

  JSON.parse(response.body) if response.body
end

def extract_topics_names(topics)
  topics.map {|topic| topic["name"]}
end

def delete_topic(base_url, topic)
  puts "Deleting topic #{topic['name']}"
  encoded_name = CGI::escape(topic['name'])
  delete_url = "#{base_url}/api/exchanges/%2f/#{encoded_name}"
  delete_request(delete_url)
end

def clean_orphan_from_sub(http_url, amqp_url, domain)
  url = "#{http_url}/api/exchanges"
  sub_topics = get_request(url)

  local_sub_topics = filter_topics_with_pattern(sub_topics, "^fed-#{domain}.*")

  for topic in local_sub_topics
    topic_url = "#{amqp_url}/#{topic['name']}"
    puts topic_url
    `omf_send_request -a -r #{topic_url}`
  end

end

def clean_orphan_topics(config)
  puts "Cleaning orphan topics: #{config}"
  subauthorities = config[:subauthorities]

  for subauthority in subauthorities
    domain = subauthority[:domain]
    base_http_url = subauthority[:http_url]
    base_amqp_url = subauthority[:amqp_url]

    clean_orphan_from_sub(base_http_url, base_amqp_url,domain)
  end

end

clean_orphan_topics(config)
